import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import LayoutWrapper from "./layout-wrapper";
import { Outfit } from "next/font/google";

const outfit = Outfit({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-outfit",
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Software Developer - Bagus Arya",
  description: "Generated by create next app",
  icons: {
    icon: "/a.svg", 
  },
    keywords: ["Bagus Arya", "Bagus Arya Portofolio", "Gede Bagus Arya"],
  openGraph: {
    title: "arzz portofolio",
    description: "x",
    url: "https://fullstack-developer-bagusarya.vercel.app/",
    siteName: "Frontend-Developer",
    images: [
      {
        url: "https://fullstack-developer-bagusarya.vercel.app/a.svg",
        width: 1200,
        height: 630,
      },
    ],
    locale: "id_ID",
    type: "website",
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${outfit.variable} antialiased`}
      >
        <LayoutWrapper>{children}</LayoutWrapper>
      </body>
    </html>
  );
}
